global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'main_backend'
    metrics_path: /api/metrics
    static_configs:
      - targets: [ 'webapp:8080' ]